using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace NOTFireEmblem
{
    
    public partial class Titlescreen : Form
    {
        /*
        CITATIONS:
        Windows site
        Stackoverflow.com

        */
        //All graphics are user generated by Alex and Dylan

        public static string P1Name;
        public static string P2Name;
        public Titlescreen()
        {
            InitializeComponent();
        }

        public void Titlescreen_Load(object sender, EventArgs e)
        {

        }

        public void StartButton_Click(object sender, EventArgs e)
        {
            //Probably not relevant anymore
            /*bool P1NameCheckB;
            bool P2NameCheckB;
            string P1NameCheck = P1NameBox.Text;
            string P2NameCheck = P2NameBox.Text;
            P1NameCheckB = Convert.ToBoolean(P1NameCheck);
            P2NameCheckB = Convert.ToBoolean(P2NameCheck);
            */
            if (string.IsNullOrEmpty(P1NameBox.Text))
            {
                P1NameBox.Text = ("Player1");

            }
            else if(string.IsNullOrEmpty(P2NameBox.Text))
            {
                P2NameBox.Text = ("Player2");
            }
            else
            {
                P1Name = P1NameBox.Text;
                P2Name = P2NameBox.Text;
                Visible = false;
                BattleScreenTestArea frm2 = new BattleScreenTestArea();
                BattleScreenTestArea battle = new BattleScreenTestArea();
                MapForm map = new MapForm();
                map.Visible = true;
            }
        }
        private void ExitButton_Click_1(object sender, EventArgs e)
        {
            Application.Exit();
        }

    }
}